### ISSUE TITLE
@codepathreview and @codepath

### ISSUE THREAD

**Issue by Amarpreet88** [Amarpreet88/TodoApp-Bootcamp#1]
Please review.

**Comment by Amarpreet88** [comment]
@codepathreview and @codepath

**Comment by nesquena** [comment]
Thanks for submitting the Todo app. Can you please review the section in the prework about [the readme](http://courses.codepath.com/snippets/intro_to_android/prework#heading-4-submitting-the-project) for your project? In particular, check out this [README template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true) and be sure to [include a GIF recorded with LiceCap](http://www.cockos.com/licecap/). Please ping me back here once that's complete.

**Comment by Amarpreet88** [comment]
![todo](https://cloud.githubusercontent.com/assets/6768278/12501473/6d93f3b4-c072-11e5-9d17-b9c9bc4237b3.gif)

**Comment by Amarpreet88** [comment]
Please verify now. I have made the updates. Sorry for inconvenience.

**Comment by nesquena** [comment]
Amarpreet,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 10 minute phone conversation** with us. Navigate to [today's date and onward from there](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work. 

With regards to extensions to implement, we are looking for developers with an interest in user experience and product development so be sure to focus on additional functional enhancements and/or improving the user interface of the app. In particular for your app:

 * Add a way to configure the date
 * Add SQLite persistence of the items so they persist across restarts
 * Improve the UI / UX

Once you select a slot, can you make sure to **include best number** to reach you at to the invite? Look forward to chatting soon!

**Comment by nesquena** [comment]
Also can you make sure your [README file](https://github.com/Amarpreet88/TodoApp-Bootcamp/blob/master/README.md) follows [this template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true) and includes the GIF above.

**Comment by Amarpreet88** [comment]
Thanks Nathan for your reply.

I will update the requested items. I have a quick question, may I know when
is the due to to submit the app with the enhanced features?

Also will book the call slot by tomorrow.

Thanks
Amarpreet

**Comment by nesquena** [comment]
> I have a quick question, may I know when is the due to to submit the app with the enhanced features?

If you can submit the enhancements by the 24th, that will greatly increase your chances of participating in the course.

**Comment by Amarpreet88** [comment]
![todo](https://cloud.githubusercontent.com/assets/6768278/12546520/36ca95b0-c2ff-11e5-94ae-7765865a2b6c.gif)

**Comment by nesquena** [comment]
Great to see you were able to augment your app with a few extension tasks now. As mentioned earlier, the extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world Android use cases.

After reviewing your project, I'd encourage you to add the new attributes (date / priority) back to the main list view so the user can access that information at a glance. This gives you an opportunity to enhance the UI of the todo items as well. 

Can you also please review the section in the prework about [the readme](http://courses.codepath.com/snippets/intro_to_android/prework#heading-4-submitting-the-project) for your project? In particular, check out this [README template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true) and be sure to [include the GIF above](http://www.cockos.com/licecap/).
